### ISSUE TITLE
Vorticity Display Crash

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#316]
Selecting vorticity display in the results page on a Samsung A51 crashes the app.

**Comment by kp-121** [comment]
Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at com.onrpiv.uploadmedia.pivFunctions.PivFunctions.createColorMapBitmap(PivFunctions.java:686)
        at com.onrpiv.uploadmedia.Experiment.ViewResultsActivity.createVorticityBitmap(ViewResultsActivity.java:565)
        at com.onrpiv.uploadmedia.Experiment.ViewResultsActivity.displayVortImage(ViewResultsActivity.java:540)
